alert Testing loggeralert dddalert dfgddebug fffalert Testing loggeralert ddd
alert dfgd
debug fff
alert Testing logger
alert ddd
alert dfgd
debug fff
alert Testing logger
alert ddd
alert dfgd
debug fff
alert ddd
alert dfgd
debug fff
alert Application error
ALERTALERTALERTALERTALERTALERTALERTALERTALERTALERTALERTALERTALERTALERTALERTALERTALERTALERTALERTALERTALERTALERTALERTALERT{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{}}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{}}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{}}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{}}}"\"\\\"Something went wrong\\\"\"""\"\\\"Something went wrong\\\"\"""\"\\\"Something went wrong\\\"\"""\"\\\"Something went wrong\\\"\""{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{}}}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{}}}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{}}}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{}}}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{}}}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{}}}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{}}}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{}}}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{}}}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{}}}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{}}}
["ALERT"]["ALERT","App is down","[\"john_doe\",\"[\\\"item_name\\\"]\",\"Something went wrong\"]"]["ALERT","App is down","[\"john_doe\",\"[\\\"item_name\\\"]\",\"Something went wrong\"]"]["ALERT","App is down","[\"john_doe\",\"[\\\"item_name\\\"]\",\"Something went wrong\"]"]["ALERT","App is down","[\"john_doe\",\"[\\\"item_name\\\"]\",\"Something went wrong\"]"]["ALERT","App is down","[\"john_doe\",\"[\\\"item_name\\\"]\\n\",\"Something went wrong\"]\n"]
["ALERT","App is down","[\"john_doe\",\"[\\\"item_name\\\"]\\n\",\"Something went wrong\"]\n"]
{"level":"ALERT","message":"App is down","context":"{\"user\":\"john_doe\",\"data\":\"{\\\"item\\\":\\\"item_name\\\"}\\n\",\"exception\":\"Something went wrong\"}\n"}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":{"massage":"Something went wrong","code":0,"file":"\/var\/www\/blog\/src\/Core\/Logger\/Handlers\/StreamLogHandler.php","line":33,"trace":"#0 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))\n#1 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)\n#2 \/var\/www\/blog\/src\/Core\/Http\/Exception\/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)\n#3 \/var\/www\/blog\/src\/Core\/Application\/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))\n#4 \/var\/www\/blog\/public\/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))\n#5 {main}"}}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at \/var\/www\/blog\/src\/Core\/Logger\/Handlers\/StreamLogHandler.php:33)"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at \/var\/www\/blog\/src\/Core\/Logger\/Handlers\/StreamLogHandler.php:33)"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at \/var\/www\/blog\/src\/Core\/Logger\/Handlers\/StreamLogHandler.php:33)"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at \/var\/www\/blog\/src\/Core\/Logger\/Handlers\/StreamLogHandler.php:33)#0 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))\n#1 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)\n#2 \/var\/www\/blog\/src\/Core\/Http\/Exception\/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)\n#3 \/var\/www\/blog\/src\/Core\/Application\/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))\n#4 \/var\/www\/blog\/public\/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))\n#5 {main}"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at \/var\/www\/blog\/src\/Core\/Logger\/Handlers\/StreamLogHandler.php:33)#0 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))\n#1 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)\n#2 \/var\/www\/blog\/src\/Core\/Http\/Exception\/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)\n#3 \/var\/www\/blog\/src\/Core\/Application\/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))\n#4 \/var\/www\/blog\/public\/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))\n#5 {main}\n"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at \/var\/www\/blog\/src\/Core\/Logger\/Handlers\/StreamLogHandler.php:33)#0 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))\n#1 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)\n#2 \/var\/www\/blog\/src\/Core\/Http\/Exception\/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)\n#3 \/var\/www\/blog\/src\/Core\/Application\/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))\n#4 \/var\/www\/blog\/public\/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))\n#5 {main}\n"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at \/var\/www\/blog\/src\/Core\/Logger\/Handlers\/StreamLogHandler.php:33)#0 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))\n#1 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)\n#2 \/var\/www\/blog\/src\/Core\/Http\/Exception\/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)\n#3 \/var\/www\/blog\/src\/Core\/Application\/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))\n#4 \/var\/www\/blog\/public\/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))\n#5 {main}\n"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at \/var\/www\/blog\/src\/Core\/Logger\/Handlers\/StreamLogHandler.php:33)#0 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))\n#1 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)\n#2 \/var\/www\/blog\/src\/Core\/Http\/Exception\/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)\n#3 \/var\/www\/blog\/src\/Core\/Application\/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))\n#4 \/var\/www\/blog\/public\/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))\n#5 {main}\n"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at \/var\/www\/blog\/src\/Core\/Logger\/Handlers\/StreamLogHandler.php:33)#0 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))\n#1 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)\n#2 \/var\/www\/blog\/src\/Core\/Http\/Exception\/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)\n#3 \/var\/www\/blog\/src\/Core\/Application\/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))\n#4 \/var\/www\/blog\/public\/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))\n#5 {main}"}}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at \/var\/www\/blog\/src\/Core\/Logger\/Handlers\/StreamLogHandler.php:33)#0 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))\n#1 \/var\/www\/blog\/src\/Core\/Logger\/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)\n#2 \/var\/www\/blog\/src\/Core\/Http\/Exception\/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)\n#3 \/var\/www\/blog\/src\/Core\/Application\/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))\n#4 \/var\/www\/blog\/public\/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))\n#5 {main}"}}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:33)#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))\n#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)\n#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)\n#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))\n#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))\n#5 {main}"}}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:33)#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))\n#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)\n#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)\n#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))\n#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))\n#5 {main}"}}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:33)#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))
#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)
#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)
#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))
#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#5 {main}"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"
[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:33)#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))
#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)
#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)
#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))
#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#5 {main}"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"
[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:33)#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))
#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)
#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)
#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))
#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#5 {main}"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"
[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:33)#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))
#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)
#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)
#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))
#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#5 {main}
"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"
[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:33)#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))
#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)
#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)
#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))
#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#5 {main}
"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"
[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:33)#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))
#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)
#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)
#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))
#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#5 {main}
"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"
[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:33)
#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))
#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)
#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)
#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))
#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#5 {main}
"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"
[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:33)
#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))
#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)
#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)
#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))
#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#5 {main}
"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"
[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:33)
#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))
#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)
#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)
#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))
#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#5 {main}
"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"
[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:33)
#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))
#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)
#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)
#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))
#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#5 {main}
"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:33)
#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))
#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)
#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)
#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))
#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#5 {main}
"}}{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"
[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:33)
#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))
#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)
#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)
#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))
#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#5 {main}
"}}
{"level":"ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"
[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:33)
#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))
#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)
#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)
#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))
#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#5 {main}
"}}
{"level":"unknown:\\App\\Core\\Logger\\LogLevel::ALERT","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:36 #0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord)) #1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array) #2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array) #3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception)) #4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request)) #5 {main}"}}{"level":"alert","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:36 #0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord)) #1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array) #2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array) #3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception)) #4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request)) #5 {main}"}}{"level":"alert","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:36 #0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord)) #1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array) #2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array) #3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception)) #4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request)) #5 {main}"}}{"level":"alert","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:36 #0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord)) #1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array) #2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array) #3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception)) #4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request)) #5 {main}"}}{"level":"alert","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:36 #0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord)) #1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array) #2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array) #3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception)) #4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request)) #5 {main}"}}{"level":"alert","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:36
#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))
#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)
#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)
#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))
#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#5 {main}"}}{"level":"alert","message":"App is down","context":{"user":"john_doe","data":{"item":"item_name"},"exception":"[object] (Exception(code: 0): Something went wrong at /var/www/blog/src/Core/Logger/Handlers/StreamLogHandler.php:36
#0 /var/www/blog/src/Core/Logger/Logger.php(18): App\\Core\\Logger\\Handlers\\StreamLogHandler->handle(Object(App\\Core\\Logger\\LogRecord))
#1 /var/www/blog/src/Core/Logger/Logger.php(27): App\\Core\\Logger\\Logger->addLog(Object(App\\Core\\Logger\\LogLevel), 'Testing logger', Array)
#2 /var/www/blog/src/Core/Http/Exception/ExceptionHandler.php(14): App\\Core\\Logger\\Logger->alert('Testing logger', Array)
#3 /var/www/blog/src/Core/Application/Application.php(82): App\\Core\\Http\\Exception\\ExceptionHandler->handle(Object(Exception))
#4 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#5 {main}"}}{"level":"alert","message":"Testing logger","context":{"exception":"[object] (Exception(code: 0): Testing logger at /var/www/blog/src/Core/Application/Application.php:79
#0 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#1 {main}"}}{"level":"alert","message":"Testing logger","context":{"exception":"[object] (Exception(code: 0): Testing logger at /var/www/blog/src/Core/Application/Application.php:79
#0 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#1 {main}"}}{"datetime":"2025-03-22 12:58:40","level":"alert","message":"Testing logger","context":{"exception":"[object] (Exception(code: 0): Testing logger at /var/www/blog/src/Core/Application/Application.php:79
#0 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#1 {main}"}}{"datetime":"2025-03-22 12:58:59","level":"alert","message":"Testing logger","context":{"exception":"[object] (Exception(code: 0): Testing logger at /var/www/blog/src/Core/Application/Application.php:79
#0 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#1 {main}"}}{"datetime":"2025-03-22 12:59:29","level":"alert","message":"ddd","context":[]}{"datetime":"2025-03-22 12:59:29","level":"alert","message":"dfgd","context":[]}{"datetime":"2025-03-22 12:59:29","level":"debug","message":"fff","context":[]}{"datetime":"2025-03-22 12:59:29","level":"alert","message":"Testing logger","context":{"exception":"[object] (Exception(code: 0): Testing logger at /var/www/blog/src/Core/Application/Application.php:79
#0 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#1 {main}"}}{"datetime":"2025-03-22 13:00:43","level":"alert","message":"ddd","context":[]}
{"datetime":"2025-03-22 13:00:43","level":"alert","message":"dfgd","context":[]}
{"datetime":"2025-03-22 13:00:43","level":"debug","message":"fff","context":[]}
{"datetime":"2025-03-22 13:00:43","level":"alert","message":"Testing logger","context":{"exception":"[object] (Exception(code: 0): Testing logger at /var/www/blog/src/Core/Application/Application.php:79
#0 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#1 {main}"}}
{"datetime":"2025-03-22 13:00:46","level":"alert","message":"ddd","context":[]}
{"datetime":"2025-03-22 13:00:46","level":"alert","message":"dfgd","context":[]}
{"datetime":"2025-03-22 13:00:46","level":"debug","message":"fff","context":[]}
{"datetime":"2025-03-22 13:00:46","level":"alert","message":"Testing logger","context":{"exception":"[object] (Exception(code: 0): Testing logger at /var/www/blog/src/Core/Application/Application.php:79
#0 /var/www/blog/public/index.php(20): App\\Core\\Application\\Application->handleRequest(Object(App\\Core\\Http\\Request))
#1 {main}"}}
{"datetime":"2025-03-22 13:37:28","level":"alert","message":"ddd","context":[]}
